builds:
  - id: daemon
    binary: trafikvader
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
archives:
  - id: daemon
    builds:
      - daemon
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
